name: Keep Streamlit Alive

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -sSL --max-time 15 \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            "https://logmult.streamlit.app" > /dev/null || true
