name: Keep Streamlit Alive

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://logmult.streamlit.app > /dev/null
